---
abstract: 'simple package to execute multiple parallel requests to the same host'
author:
  - unknown
build_requires:
  Test::More: '0'
  Test::TCP: '0'
configure_requires:
  Module::Build: '0.19'
dynamic_config: 0
generated_by: 'Module::Build version 0.4231, CPAN::Meta::Converter version 2.150010'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MojoX-HTTP-Async
provides:
  MojoX::HTTP::Async:
    file: lib/MojoX/HTTP/Async.pm
    version: '0.01'
requires:
  POSIX: '0'
  perl: '5.012001'
resources:
  bugtracker: https://github.com/KalessinD/perl_mojox_http_async/issues
  repository: https://github.com/KalessinD/perl_mojox_http_async
version: '0.01'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
